Performing video capture

In [1]:
import cv2,time

In [2]:
#Capturing one initial frame
video=cv2.VideoCapture(0)#As I have only one webcam I am initialising it as zero,basically using this code to open the camera
check,frame=video.read()#check is a boolean and frame is a numpy datatype
time.sleep(3)
print(check)
print(frame)#frame is the numpy version is the first image or frame that the webcam captures
cv2.imshow("Captured:",frame)
print(frame.shape)
video.release()#Stops the webcam or camera or similar devices
cv2.waitKey(0)
cv2.destroyAllWindows()

True
[[[ 29  28  44]
  [ 25  23  39]
  [  3  16  49]
  ...
  [ 17  60  70]
  [ 19  59  64]
  [ 21  61  67]]

 [[ 26  27  43]
  [ 25  26  42]
  [  8  19  50]
  ...
  [ 15  59  76]
  [ 19  60  70]
  [ 23  64  74]]

 [[ 19  26  42]
  [ 19  26  42]
  [ 12  21  50]
  ...
  [ 14  59  82]
  [ 19  61  78]
  [ 22  64  80]]

 ...

 [[  0  51  71]
  [  0  53  73]
  [  0  55  70]
  ...
  [118 149 153]
  [124 151 151]
  [124 151 151]]

 [[  0  54  64]
  [  0  57  67]
  [  0  57  69]
  ...
  [120 150 151]
  [128 151 149]
  [127 150 148]]

 [[  0  56  61]
  [  0  58  64]
  [  0  58  65]
  ...
  [119 148 150]
  [126 149 147]
  [126 149 147]]]
(480, 640, 3)


In [11]:
ord('q')

113

In [ ]:
#Capturing a whole video that can be exited by pressing q
video=cv2.VideoCapture(0)#As I have only one webcam I am initialising it as zero,basically using this code to open the camera
while True:
    check,frame=video.read()#check is a boolean and frame is a numpy datatype
    print(check)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Captured:",gray)
    key=cv2.waitKey(1)
    print(key)
    if key==ord('q'):
        break
video.release()#Stops the webcam or camera or similar devices

cv2.destroyAllWindows()